### ISSUE TITLE
Great but not that useful :\

### ISSUE THREAD

**Issue by minanagehsalalma** [irido-cyclitis/ZTE#1]
what about the orange one zxhn H108N  ?

there is no way in nor any vulnerabilities available 

hint: the default password is the pppoe username +msan or what ever 

if that helps.

**Comment by irido-cyclitis** [comment]
We're currently out of work due to studying. We don't accept any kind of vulnerability requests unless the manufacturer and the ISP knows that there's some kind of vulnerability. Once A vulnerability is discovered, steps will be taken and the vulnerability will be disclosed as soon as it fixed.
Thanks for your inquiry

**Comment by minanagehsalalma** [comment]
@irido-cyclitis oh hi mate , btw did they give you any bounty for CVE-2019-3420 ? considering that the router is a bit old and that bug is only in the tedata/we version of the router only.

>We don't accept any kind of vulnerability requests unless the manufacturer and the ISP knows that there's some kind of vulnerability

so is there any kind of bounty as mostly the routers firmware here are modified by the ISPs .... do you report it to the isp or the  manufacturer  ? 


also you seem like you forgot to report this [Huawei HG630 2 Router - Authentication Bypass](https://www.exploit-db.com/exploits/48310) as it says #CVE: N/A  ::\

**Comment by irido-cyclitis** [comment]
@minanagehsalalma Hello, I can neither confirm nor deny that I received a bounty, it's not allowed to disclose such information.
And yes, I report it to the manufacturer then they inform the ISP. There's a modified version of every router firmware "probably for spying haha". The modified firmwares actually doesn't differ much from original firmwares, and they reproduce it to check if it's working. The manufacturer has a copy of every modified version.
Also, Any reports sent to ZTE only. Since I signed a letter of commitment with them. Before you ask, I shall not disclose the letter or the bounties or the Vulnerabilities before reporting.

**Comment by irido-cyclitis** [comment]
The vulndb bounty range is not accurate "a huge difference between 0 dollars and 5k dollars and this range is based on CVSSV3.0 score".
For the firmware stuff, paths and GUI differ, mechanism is the same.

**Comment by minanagehsalalma** [comment]
> For the firmware stuff, paths and GUI differ, mechanism is the same.

@irido-cyclitis  not really that file isn't even there , "mechanism " is not an accurate word to describe this.

so anyway what about this ?

> anyway if i happened to find a bug how would i get the bounty back ? via what ?

**Comment by irido-cyclitis** [comment]
You can get it as a bank transfer or a gift card

**Comment by minanagehsalalma** [comment]
> You can get it as a bank transfer or a gift card

@irido-cyclitis huh , get it as what ? YO bro we are in egypt.

you are not allowed to have a visa till you are 21yo.

**Comment by irido-cyclitis** [comment]
off-topic questions will be ignored. You came for a technical issue and now you're talking about payment. All the available information are given to you. No personal questions.

**Comment by minanagehsalalma** [comment]
> off-topic questions will be ignored. You came for a technical issue and now you're talking about payment. All the available information are given to you. No personal questions.

@irido-cyclitis  okay . i think i found a vuln in one of the devices that are in the bounty list 

should i sell it on the deep web or report it or sell it then report it ? 😏 

i am kidding , wanna collab later ?

**Comment by irido-cyclitis** [comment]
Reporting it will be more rewarding.

**Comment by minanagehsalalma** [comment]
> Reporting it will be more rewarding.

@irido-cyclitis in which terms ?

**Comment by minanagehsalalma** [comment]
> We don't accept any kind of vulnerability requests unless the manufacturer and the ISP knows that there's some kind of vulnerability.

@irido-cyclitis  I'd say that this some kind of hypocrisy ...right? 
![Screenshot_2020-12-22_232348-1](https://user-images.githubusercontent.com/20546638/102934780-80734100-44ad-11eb-8c4d-bde04fea1f8d.jpg)
And he even edited the post to remove the text before closing the issue ... when i confronted him ... i was even joking lol , why did he took it so serious ?

**Comment by irido-cyclitis** [comment]
@Zeyad-Azima knows what he's doing. 
I "morad as a person" don't accept any kind of vulnerability requests.
If you have a problem with @Zeyad-Azima , figure it out with him. If you have any other problems, please contact morad.gill@gmail.com
